name: autodiff

channels:
  - conda-forge
  - nvidia

dependencies:
  - catch2>=3
  - ccache
  - clangxx_osx-64  # [osx]
  - cmake
  - doxygen=1.9.1  # [linux]
  - eigen
  - git
  - graphviz  # [linux]
  - gxx_linux-64  # [linux]
  - lld  # [linux]
  - make  # [unix]
  - mkdocs
  - mkdocs-macros-plugin
  - mkdocs-material
  - ninja
  - pip
  - pre-commit
  - pybind11
  - pybind11-abi
  - pybind11-stubgen
  - python=3.10
  - shellcheck
  - cuda-toolkit  # [linux]
